version: '3.8'

services:
  # Web API
  api:
    build: .
    container_name: law-api
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Redis - Message Broker and Result Backend
  redis:
    image: redis:6.2-alpine
    container_name: law-redis
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis-data:/data
    restart: unless-stopped

  # Celery Worker for Document Processing
  worker-documents:
    build: .
    container_name: law-worker-documents
    command: celery -A celery_config worker -Q documents -l info
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    restart: unless-stopped

  # Celery Worker for OCR Processing
  worker-ocr:
    build: .
    container_name: law-worker-ocr
    command: celery -A celery_config worker -Q ocr -l info
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    restart: unless-stopped

  # Celery Worker for Extraction
  worker-extraction:
    build: .
    container_name: law-worker-extraction
    command: celery -A celery_config worker -Q extraction -l info
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    restart: unless-stopped

  # Celery Beat for Scheduled Tasks
  beat:
    build: .
    container_name: law-beat
    command: celery -A celery_config beat -l info
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    restart: unless-stopped

  # Flower - Celery Monitoring (optional)
  flower:
    build: .
    container_name: law-flower
    command: celery -A celery_config flower --port=5555
    ports:
      - "5555:5555"
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - worker-documents
    restart: unless-stopped

volumes:
  redis-data: